### ISSUE TITLE
2 Dast 2 Continuous - Autenticación con OWASP ZAP 

### ISSUE THREAD

**Issue by irequena-dev** [CybercampHackathon2019/ayuda#1]
Necesitamos lanzar un full scan con OWASP ZAP por linea de comandos pero no conseguimos pasarle las credenciales para que se autentique en la página web.
¿Alguien nos puede orientar?

**Comment by Rafa-s-r** [comment]
Con _-config_ podéis pasarle la configuración https://github.com/zaproxy/zaproxy/wiki/FAQconfigValues

Y podéis leer esto (https://github.com/zaproxy/zaproxy/wiki/FAQformauth) que quizás os ayude!!

Si no, podéis llegaros a la mesa de AllPentesting!!

**Comment by irequena-dev** [comment]
Muchas gracias compañero!
Por desgracia esa solución no parece funcionar :'(

**Comment by irequena-dev** [comment]
Hemos conseguido solucionarlo finalmente.
