### ISSUE TITLE
Increase xterm size

### ISSUE THREAD

**Issue by Aws0mus** [CybercampHackathon2019/ayuda#4]
Our CTF platform runs different xterm consoles inside Mininet from each component. We need to know how to increase the font size by default.

Is there any expert on xterm who can help us?

**Comment by bluebycode** [comment]
Yep, try this out:
Terminal class, it's supposed to be the xterm.js class instance by term
 ```
const term = new Terminal({
  cursorBlink: true,
  rows: 12,
  cols: 80,
  fontSize: 11 *****
  })
```
More extra options designed from official: https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#fontsize

Don't hesitate to ask me for more xterm.js - "frustrating stuff"

This reference helped me a lot: https://www.linkedin.com/pulse/xtermjs-local-echo-ioannis-charalampidis/

Hope this resolve ur question! :)

**Comment by Aws0mus** [comment]
We managed to increase the xterm size by changing the default settings.

Creating the file ~/.Xresources and adding the following lines:
```
xterm*geometry: 60x20
xterm*faceSize: 35
xterm*font:  10x20
```
Then, loading the new configuration:
```
xrdb -merge ~/.Xresources
```
