### ISSUE TITLE
ESWifi - Code analysis checkers

### ISSUE THREAD

**Issue by maesbrisa** [CybercampHackathon2019/ayuda#5]
Hi!

We are MEFS and our project is ESWifi (the routers project one ). 

Our Ionic multiplatform application needs some checks to improve our CI pipelines. We started using Github Actions to build apk artifacts and check dependencies using lint.

Any suggestions? Thanks in advance.

**Comment by CarlosLannister** [comment]
Here you have:
- https://lgtm.com/
- https://sonarcloud.io/

Also, do not forget to scan third party dependencies: 
- https://snyk.io/

**Comment by maesbrisa** [comment]
Cool, we'll try both. I 've already integrate Snyk with the repo.

Also I found one for npm projects to check dependencies along with npm audit (https://greenkeeper.io/).

Thank you @CarlosLannister :)
