### ISSUE TITLE
Any available PC to test ASSAP?

### ISSUE THREAD

**Issue by nereasainzdelamaza** [CybercampHackathon2019/ayuda#6]
Hello

We are UnicornTeam and our project is ASSAP (Anti Shoulder Surfing Attack Platform).

We would like to test our project in other platforms apart from Mac. Any available PC?

Thanks in advance.

**Comment by Miguel000** [comment]
MEFs Team has one to test :)

**Comment by dankitan** [comment]
In our team (KM11), we have the three main operating systems (Mac, Windows and Linux). If you need any help, feel free to ask. Greets.

**Comment by nereasainzdelamaza** [comment]
Thank you! We have already tested it. When we have new releases, we would ask you.
